include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: ["**/*.g.dart", "lib/generated/**", "**/*.chopper.dart"]
  errors:
    asset_does_not_exist: ignore

linter:
  rules:
    always_use_package_imports: true
    avoid_renaming_method_parameters: false
    always_declare_return_types: true
    sized_box_for_whitespace: true
    avoid_multiple_declarations_per_line: true
    prefer_final_in_for_each: true
    unnecessary_lambdas: true
    avoid_print: true
