# https://joshuamdeguzman.com/continuous-delivery-for-flutter-using-fastlane-and-github-actions-pt-2-android/
default_platform(:android)

PACKAGE_NAME = ENV["PACKAGE_NAME"]
FLAVOR = ENV["FLAVOR"]

platform :android do
  lane :apply_new_version do
    flutter_version_manager(
      arguments: "-apply",
      yml: "../version.yml",
      pubspec: "../pubspec.yaml",
      git_repo: "..")
  end

  desc "Build and deploy app to the PlayStore"
  lane :build_and_deploy do
    begin
      upload_to_play_store(
        package_name: "#{PACKAGE_NAME}",
        track: 'internal',
        aab: "../build/app/outputs/bundle/#{FLAVOR}Release/app-#{FLAVOR}-release.aab",
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        release_status: "draft",
        version_code: flutter_version()["version_code"],
      )
    end
  end
end
