default_platform(:android)

platform :android do
  lane :apply_new_version do
    flutter_version_manager(
      arguments: "-apply",
      yml: "../version.yml",
      pubspec: "../pubspec.yaml",
      git_repo: "..")
  end

  desc "Build and deploy app to the PlayStore"
  lane :build_and_deploy do
    begin
      gradle(task: "clean")
      gradle(
        task: "bundle",
        build_type: 'Release'
      )
      upload_to_play_store(
        track: 'internal',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        release_status: "completed",
        version_code: flutter_version()["version_code"],
      )
    end
  end
end
