name: Publish Android
env:
  FLUTTER_VERSION: '3.3.8'

on:
  workflow_call:
    secrets:
      ANDROID_KEYS_SECRET_PASSPHRASE:
        required: true
      DART_DEFINE_API_KEY_DEV:
        required: true
      DART_DEFINE_API_KEY_PROD:
        required: true
      DART_DEFINE_API_URL_DEV:
        required: true
      DART_DEFINE_API_URL_PROD:
        required: true
    inputs:
      environment:
        description: 'String value that determines if production or dev packages are built'
        default: 'dev'
        required: true
        type: string
      testBuild:
        description: 'Boolean value which triggers only building the application without publishing'
        default: true
        required: true
        type: boolean
      major:
        required: false
        type: string
      minor:
        required: false
        type: string
      patch:
        required: false
        type: string

jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Build Android
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_secrets.sh
        env:
          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - uses: actions/download-artifact@v3
        with:
          name: generated-files-and-packages

      - name: Write version to the version.yml
        if: ${{ inputs.testBuild == false }}
        run: |
          echo "---" > ./version.yml
          echo "major: ${{ inputs.major }}" >> ./version.yml
          echo "minor: ${{ inputs.minor }}" >> ./version.yml
          echo "patch: ${{ inputs.patch }}" >> ./version.yml
          tail ./version.yml

      - name: Give write permissions to needed paths
        if: ${{ inputs.testBuild == false }}
        run: cd /var && sudo chmod -R a+w lib/

      - name: Set version
        if: ${{ inputs.testBuild == false }}
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: apply_new_version
          subdirectory: android

      - name: Build production version
        if: ${{ inputs.environment == 'production' }}
        run: flutter build appbundle --release --flavor production --dart-define=IS_PROD=true --dart-define=API_URL=${{ secrets.DART_DEFINE_API_URL_PROD }} --dart-define=API_KEY=${{ secrets.DART_DEFINE_API_KEY_PROD }}

      - name: Build dev version
        if: ${{ inputs.environment == 'dev' }}
        run: flutter build appbundle --release --flavor dev --dart-define=IS_PROD=true --dart-define=API_URL=${{ secrets.DART_DEFINE_API_URL_DEV }} --dart-define=API_KEY=${{ secrets.DART_DEFINE_API_KEY_DEV }}

      - name: Run Fastlane
        if: ${{ inputs.testBuild == false }}
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: build_and_deploy
          subdirectory: android
          env: ${{ inputs.environment }}
