name: Run e2e tests in all infrastructure branches

on:
  push:
    branches:
      - 'infrastructure/**'
  workflow_dispatch:

jobs:
  run-tests:
    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@master
    with:
      e2e: true
      unitTests: false
