name: UnitTests

on:
  push:
    branches:
      - 'task/**'
      - 'feature/**'
  workflow_dispatch:

jobs:
  run-tests:
    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@bug/master
    with:
      e2e: false
      unitTests: true
