name: ALL IntegrationTests/UnitTests

on:
  push:
    branches:
      - 'test/**'
  workflow_dispatch:

jobs:
  run-tests:
    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@bug/master
    with:
      e2e: true
      unitTests: true
