name: Run e2e and unit tests in all test/feature/task branches

on:
  push:
    branches:
      - 'test/**'
      - 'feature/**'
      - 'task/**'
  workflow_dispatch:

jobs:
  run-tests:
    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@test/fix_long_execution
    with:
      e2e: true
      unitTests: true
