name: UnitTests

on:
  push:
    branches:
      - 'task/**'
      - 'feature/**'
  workflow_dispatch:

jobs:
  run-tests:
    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@task/134-tapbar-with-updated-ui
    with:
      e2e: false
      unitTests: true
